# Generated by Django 3.0.5 on 2020-05-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_management', '0003_auto_20200503_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='user_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='text',
            name='category',
        ),
        migrations.AddField(
            model_name='text',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='text_management.Category'),
        ),
        migrations.AlterField(
            model_name='text',
            name='link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
