# Generated by Django 3.0.5 on 2020-05-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_management', '0004_auto_20200503_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='complexity',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=20),
            preserve_default=False,
        ),
    ]
