# Generated by Django 3.0.6 on 2020-05-19 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_management', '0005_text_complexity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['text__pk', '-frequency']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_texts', to='text_management.Category'),
        ),
        migrations.AlterField(
            model_name='text',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_texts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserTextSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist_string', models.TextField(default='')),
                ('min_characters', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_text_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
