# Generated by Django 3.0.6 on 2020-05-20 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_management', '0006_auto_20200519_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertextsettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_analysis', to='text_management.Text'),
        ),
        migrations.AlterField(
            model_name='usertextsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_text_settings', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
