# Generated by Django 3.0.5 on 2020-05-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200501_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
